import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HeaderTop from "@/components/HeaderTop";
import HeaderMain from "@/components/HeaderMain";
import Footer from "@/components/Footer";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Corten+",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderTop />
        <HeaderMain />
        {/*<Navbar />*/}
        {children}
<<<<<<< HEAD
        <br /><br /><br /><br /><br /><br /> 
=======
>>>>>>> 9f62ce009674dfabd2a6f5cf3fbf64d9b8ee5e3a
        <Footer />
      </body>
    </html>
  );
}
